# Copyright Siemens AG, 2014-2018
# SPDX-License-Identifier:	GPL-2.0 LGPL-2.1

# build FOSSology on Travis CI - https://travis-ci.org/

language: php
dist: trusty
php: 7.0

addons:
  apt:
    packages: &default_packages
      - cabextract
      - genisoimage
      - libboost-program-options-dev
      - libboost-regex-dev
      - libcppunit-dev
      - libcunit1-dev
      - libdbd-sqlite3-perl
      - libjsoncpp-dev
      - libjson-c-dev
      - liblocal-lib-perl
      - libmagic-dev
      - librpm-dev
      - libspreadsheet-writeexcel-perl
      - libtext-template-perl
      - php5-cli
      - php5-pgsql
      - poppler-utils
      - p7zip
      - p7zip-full
      - rpm
      - sleuthkit
      - unrar-free
      - upx-ucl

services: postgresql

sudo: false

jobs:
  include:
#### PHPUnit tests ###########################
    - &phpunit-tests
      php: 5.6
      sudo: required
      install: composer install --prefer-dist --working-dir=src
      before_script: ./utils/prepare-test -afty
      script:
        - make build-lib VERSIONFILE build-cli
        - src/vendor/bin/phpunit -csrc/phpunit.xml --testsuite="Fossology PhpUnit Test Suite"
    - <<: *phpunit-tests
      php: 7.0
    - <<: *phpunit-tests
      php: 7.1
      install: composer update --ignore-platform-reqs --with-dependencies --prefer-dist --working-dir=src phpunit/phpunit
    - <<: *phpunit-tests
      php: 7.2
      install: composer update --ignore-platform-reqs --with-dependencies --prefer-dist --working-dir=src phpunit/phpunit
    - <<: *phpunit-tests
      php: 7.2
      env: PGPORT=5432
      addons:
        postgresql: "10"
        apt:
          packages:
            - *default_packages
            - postgresql-10
            - postgresql-client-10
      before_script: *postgres-before-script
      install: composer update --ignore-platform-reqs --with-dependencies --prefer-dist --working-dir=src phpunit/phpunit
    - stage: GitHub Page Release
      name: GitHub Page deploy
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      script:
        - doxygen -v
        - bash utils/deploy-pages.sh
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: false
        local-dir: ./code_docs
        repo: $GH_REPO_REF
        target-branch: master
        on:
          branch: master
  allow_failures:
    - name: Copy/Paste Detector
