# Copyright Siemens AG, 2014-2018
# SPDX-License-Identifier:	GPL-2.0 LGPL-2.1

# build FOSSology on Travis CI - https://travis-ci.org/

language: php
dist: trusty
php: 7.0
cache:
  ccache: true
  directories:
    - $HOME/.composer
env:
  global:
    - PATH="/usr/lib/ccache/:$PATH"
    - COMPOSER_HOME="$HOME/.composer/"

addons:
  apt:
    packages: &default_packages
      - cabextract
      - genisoimage
      - libboost-program-options-dev
      - libboost-regex-dev
      - libcppunit-dev
      - libcunit1-dev
      - libdbd-sqlite3-perl
      - libjsoncpp-dev
      - libjson-c-dev
      - liblocal-lib-perl
      - libmagic-dev
      - librpm-dev
      - libspreadsheet-writeexcel-perl
      - libtext-template-perl
      - php5-cli
      - php5-pgsql
      - poppler-utils
      - p7zip
      - p7zip-full
      - rpm
      - sleuthkit
      - unrar-free
      - upx-ucl

services: postgresql

jobs:
  include:
    - &phpunit-tests
      php: 5.6
      addon: {}
      install: composer install --prefer-dist --working-dir=src
      before_script: ./utils/prepare-test -afty
      script:
        - make build-lib VERSIONFILE build-cli
        - src/vendor/bin/phpunit -csrc/phpunit.xml --testsuite="Fossology PhpUnit Test Suite"
      after_success: php src/vendor/bin/coveralls -x clover.xml
    - &php7-phpunit-tests
      <<: *phpunit-tests
      php: 7.0
      before_install: phpenv config-rm xdebug.ini
      script:
        - make build-lib VERSIONFILE build-cli
        - phpdbg -qrr src/vendor/bin/phpunit -csrc/phpunit.xml --coverage-clover clover.xml --testsuite="Fossology PhpUnit Test Suite"
    - &php71-phpunit-tests
      <<: *php7-phpunit-tests
      php: 7.1
      install: composer update --ignore-platform-reqs --with-dependencies --prefer-dist --working-dir=src phpunit/phpunit
  allow_failures:
    - name: Copy/Paste Detector
